export const LOAD_LOGIN_USER_ATTRIBUTES_SUCCESS = "LOAD_LOGIN_USER_ATTRIBUTES_SUCCESS";
export const LOGOUT_USER_REMOVE_ATTRIBUTES_SUCCESS = "LOGOUT_USER_REMOVE_ATTRIBUTES_SUCCESS";

export const LOAD_CENTERS_SUCCESS = "LOAD_CENTERS_SUCCESS";
export const ADD_CENTERS = "ADD_CENTERS";
export const UPDATE_SELECTED_LOCATE_CENTER = "UPDATE_SELECTED_LOCATE_CENTER";

export const UPDATE_LOGIN_STATE = "UPDATE_LOGIN_STATE";

