/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e00ab7e7-51dd-4e27-bb2c-a61ea2fc0855",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hw7RbHhPK",
    "aws_user_pools_web_client_id": "7n8jsputummmvsede76mtsd1nt",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://cvq5daqv6fe7lmv3xw76hqyr4e.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xufk5ahsznhqvjgj326vyrixd4",
    "aws_content_delivery_bucket": "findvac-20210312232413-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://findvac-20210312232413-hostingbucket-dev.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
